# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.dotechnology.cn:

networks:
  byfn:
services:
  orderer.dotechnology.cn:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dotechnology.cn
    container_name: orderer.dotechnology.cn
    extra_hosts:
      - "kafka0:192.168.240.26"
      - "kafka1:192.168.240.28"
      - "kafka2:192.168.240.29"
    networks:
      - byfn
