# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.dotechnology.cn:
    container_name: orderer.dotechnology.cn
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
       # kafka
      - ORDERER_KAFKA_RETRY_LONGINTERVAL=10s
      - ORDERER_KAFKA_RETRY_LONGTOTAL=100s
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/dotechnology.cn/orderers/orderer.dotechnology.cn/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/dotechnology.cn/orderers/orderer.dotechnology.cn/tls/:/var/hyperledger/orderer/tls
    - orderer.dotechnology.cn:/var/hyperledger/production/orderer
    ports:
      - 7050:7050



  peer0.org1.dotechnology.cn:
    container_name: peer0.org1.dotechnology.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.dotechnology.cn
      - CORE_PEER_ADDRESS=peer0.org1.dotechnology.cn:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.dotechnology.cn:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.dotechnology.cn:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.dotechnology.cn:7052
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.dotechnology.cn/peers/peer0.org1.dotechnology.cn/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.dotechnology.cn/peers/peer0.org1.dotechnology.cn/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.dotechnology.cn:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.org2.dotechnology.cn:
    container_name: peer0.org2.dotechnology.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.dotechnology.cn
      - CORE_PEER_ADDRESS=peer0.org2.dotechnology.cn:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.dotechnology.cn:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.dotechnology.cn:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.dotechnology.cn:7052
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.dotechnology.cn/peers/peer0.org2.dotechnology.cn/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.dotechnology.cn/peers/peer0.org2.dotechnology.cn/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.dotechnology.cn:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

